config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @list = List.find(params[:list_id])
    @bookmarks = @list.bookmarks
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to list_bookmarks_path(@list), notice: 'Bookmark was successfully added.'
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(lists_params)
    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def lists_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks for <%= @list.name %></h1>

<table>
  <thead>
    <tr>
      <th>Movie Title</th>
      <th>Comment</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.movie.title %></td>
        <td><%= bookmark.comment %></td>
        <td>
          <%= link_to 'Edit', edit_list_bookmark_path(@list, bookmark) %> |
          <%= link_to 'Delete', list_bookmark_path(@list, bookmark), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Lists', lists_path %>
<%= link_to 'Add a new Bookmark', new_list_bookmark_path(@list) %>

app/views/bookmarks/new.html.erb
<h1>Add a new bookmark to <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, label_method: :title, value_method: :id, include_blank: false %>
  <%= f.input :comment %>
  <%= f.button :submit, 'Add Bookmark' %>
<% end %>

<%= link_to 'Back', list_bookmarks_path(@list) %>

<%# THIS ONE IS THE ONE THAT DOESNT WORK %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/index.html.erb
<ul>
  <% @lists.each do |list|%>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
  </ul>

<p><%= link_to "Add List", new_list_path %></p>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<p><%= link_to 'Back to lists', lists_path %></p>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

  <p>
  <%= link_to 'Back to lists', lists_path %>
  <%= link_to 'View movies', list_bookmarks_path(@list) %>
  </p>
</div>